### ISSUE TITLE
Flutter-UI-Kit-master-android-app-build.gradle' line: 16

### ISSUE THREAD

**Issue by NTMS2017** [iampawan/Flutter-UI-Kit#1]
**Hi Pawan,

I am having these issues. Do you know how to correct the issue.**

Running "flutter packages get" in Flutter-UI-Kit-master...
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: /Users/niyazitoros/Downloads/Flutter-UI-Kit-master/android/gradlew app:properties:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/niyazitoros/Downloads/Flutter-UI-Kit-master/android/app/build.gradle' line: 16

Finished with error: Please review your Gradle project setup in the android/ folder.
* What went wrong:
A problem occurred evaluating project ':app'.
> versionCode not found. Define flutter.versionCode in the local.properties file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by iampawan** [comment]
Readme updated. Please check

**Comment by PositiveVibration1** [comment]
hey am experiencing the same problem Finished with error: Please review your Gradle project setup in the android/ folder.
How do can i solve this

**Comment by oiar** [comment]
How do can I solve the same problem.

**Comment by SergioRe** [comment]
Someone solved the problem???

**Comment by iampawan** [comment]
Yes  Its solved
