### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by prathapbez** [iampawan/Flutter-UI-Kit#10]
Hi Pawan,

Thank you for your posts.

I am unable to compile the build which i took from master branch can you please look the below log and kindly let me know what i am doing wrong.

Thanks in advance.

compiler message: lib/ui/page/home_page.dart:303:17: Error: No named parameter with the name 'border'.
compiler message:                 border: Border(bottom: BorderSide.none),
compiler message:                 ^^^^^^
compiler message: file:///Users/prathap/Documents/Flutter%20Development/flutter/packages/flutter/lib/src/cupertino/nav_bar.dart:191:9: Context: Found this candidate, but the arguments don't match.
compiler message:   const CupertinoSliverNavigationBar({
compiler message:         ^
compiler message: lib/ui/widgets/common_scaffold.dart:33:16: Error: Method not found: 'CircularNotchedRectangle'.
compiler message:         shape: CircularNotchedRectangle(),
compiler message:                ^^^^^^^^^^^^^^^^^^^^^^^^
compiler message: lib/ui/widgets/common_scaffold.dart:33:9: Error: No named parameter with the name 'shape'.
compiler message:         shape: CircularNotchedRectangle(),
compiler message:         ^^^^^
compiler message: file:///Users/prathap/Documents/Flutter%20Development/flutter/packages/flutter/lib/src/material/bottom_app_bar.dart:45:9: Context: Found this candidate, but the arguments don't match.
compiler message:   const BottomAppBar({
compiler message:         ^
Compiler failed on /Users/prathap/Desktop/Flutter/Flutter-UI-Kit/lib/main.dart
Error launching application on iPhone X.

**Comment by agirot** [comment]
Same here :/

**Comment by agirot** [comment]
You can just comment two line and run the project if you just want discover the project like me:

`lib/ui/widgets/common_scaffold.dart`
```
@@ -30,7 +30,7 @@ class CommonScaffold extends StatelessWidget {
       this.elevation = 4.0});

   Widget myBottomBar() => new BottomAppBar(
+        //shape: CircularNotchedRectangle(),
```

and
`lib/ui/page/home_page.dart`
```
class HomePage extends StatelessWidget {
           child: CustomScrollView(
             slivers: <Widget>[
               CupertinoSliverNavigationBar(
-                //border: Border(bottom: BorderSide.none),
```

**Comment by iampawan** [comment]
It's happening because of the change in the flutter sdk, so please let me know your flutter sdk versions as well

**Comment by prathapbez** [comment]
This is my Version-Flutter 0.5.1

**Comment by iampawan** [comment]
That is beta. That's why you are facing issues. Switch to dev or master
