### ISSUE TITLE
build for iOS failed

### ISSUE THREAD

**Issue by wackyapps** [iampawan/Flutter-UI-Kit#12]
Waqass-Mac:flutter-ui-kit waqas$ flutter run
Launching lib/main.dart on iPhone 6 in debug mode...
Starting Xcode build...                                          
Xcode build done.                                            1.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
Could not build the application for the simulator.
Error launching application on iPhone 6.

Kindly guide what to do to run this on iOS Simulator

**Comment by Ahmet-Kaplan** [comment]
you should run :
cd ios
pod install

**Comment by iampawan** [comment]
Just go to your ios folder and then run pod install and it will work

**Comment by krnblni** [comment]
If you have Cocoapods correctly installed, "pod install" will run by default.
This removes a lot of overhead. ✌️
Correct me if I'm wrong.
