### ISSUE TITLE
text widgets overflowing from credit card in credit card page

### ISSUE THREAD

**Issue by parth181195** [iampawan/Flutter-UI-Kit#15]
![flutter_02](https://user-images.githubusercontent.com/17850142/45728781-2bb63100-bbe7-11e8-97cd-7aa85c4889e9.png)
i will submit a pr for this issue

**Comment by parth181195** [comment]
it also causes the issue in landscape mode cause we are defining hight as 1/3 of the screen we should make it of a constant height

**Comment by iampawan** [comment]
The app is not yet optimized for landscape mode and I opened this
orientation just to see how many users actually use it. Regarding the
overflow pixels, that needs to be fixed so I'll fix it in the next update.

**Comment by parth181195** [comment]
then should we use a fixed height for the card or increase the ratio from 0.3 to 0.4

**Comment by iampawan** [comment]
Fixed
