### ISSUE TITLE
I couldn't run this app

### ISSUE THREAD

**Issue by jacksun0124** [iampawan/Flutter-UI-Kit#17]
I downloaded this app and opened with VS Code. But I couldn't run it. 

I got an error message like this:

  `> C:\Users\just0\Desktop\flutter_apps\Flutter-UI-Kit-master\android\key.properties (The system cannot find the file specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Please review your Gradle project setup in the android/ folder.
Exited (sigterm)`

**Comment by edgartrem** [comment]
You should go back and read the README, there's literally a section that talks about `If you try to build the project straight away, you'll get an error complaining that a key.properties file is missing and Exit code 1 from: /Flutter-UI-Kit-master/android/gradlew app:properties:. To resolve that,`

**Comment by jacksun0124** [comment]
@edgartrem Thanks
