### ISSUE TITLE
issue with footer image

### ISSUE THREAD

**Issue by moda20** [iampawan/Flutter-UI-Kit#18]
![screenshot_20180927-221757](https://user-images.githubusercontent.com/23613485/46175394-b9f37c80-c2a3-11e8-995c-71ab108d4346.png)

I am reporting that the button in the middle is supposed to be a circle theme and the footer is supposed to be shaped around it, but as you see in my screenshot that is not happening, 
What is the problem ?

**Comment by iampawan** [comment]
Fixed
