### ISSUE TITLE
 dashboard 2 onPressed doesnt work

### ISSUE THREAD

**Issue by NTMS2017** [iampawan/Flutter-UI-Kit#19]
Hi Pawan,

The dashboard 2 onPressed doesnt work

 new SizedBox.fromSize(
                  size: Size.square(_myWidth / 5),
                  child: Card(
                    color: Colors.yellow.shade900,
                    child: LabelBelowIcon(
                      betweenHeight: 5.0,
                      icon: Icons.shop,
                      label: "Harcama",
                      iconColor: Colors.white,
                      isCircleEnabled: false,
                      onPressed: () {
                        Navigator.pop(
                            context,
                            new MaterialPageRoute(
                                builder: (context) =>
                                    new MySpending(title: "MySpending")));
                      },
                    ),
                  ),
                ),

**Comment by iampawan** [comment]
Dashboard 2 opens on Press and then it is not supposed to work further

**Comment by NTMS2017** [comment]
Hi Pawan,

In dashboard 2 opens on press and shows the "Pay Your Bills" buttons like you design using the new SizedBox.fromSize. When I look at your code there is however its a onTab settings. So when I try with above code I didn't pop or push to new page. Thanks
