### ISSUE TITLE
http package missing in pubspec.yaml

### ISSUE THREAD

**Issue by hendrx** [iampawan/Flutter-UI-Kit#21]
flutter run fails with:

Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  /Users/arnehendricks/work/flutter_kram/Flutter-UI-Kit/lib/services/restclient.dart
...refers, in an import, to the following library:
  package:http/http.dart
That library is in a package that is not known. Maybe you forgot to mention it in your pubspec.yaml file?

**Comment by hendrx** [comment]
i added http package to pubspec.yaml, will make a PR

**Comment by hendrx** [comment]
https://github.com/iampawan/Flutter-UI-Kit/pull/22

**Comment by esambinava** [comment]
I just run it and i face the sane isuue mentioned above 
Please help
Thanks

**Comment by Jerry254** [comment]
How to use the http package:
* https://pub.dartlang.org/packages/http

**Comment by Brixto** [comment]
@iampawan this issue is kinda old now, and some PRs have been raised to address this. Will one of them be merged soon?

**Comment by iampawan** [comment]
Merged and Fixed. Sorry for the delay.
