### ISSUE TITLE
flutter run --release error

### ISSUE THREAD

**Issue by xuzhengrong1** [iampawan/Flutter-UI-Kit#28]
flutter run --release
Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
cause the error,
Failed to find snapshot: /var/containers/Bundle/Application/5C5E8099-6007-4E7C-9F95-8097BD9C2F7E/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
[VERBOSE-2:engine.cc(116)] Engine run configuration was invalid.
[VERBOSE-2:FlutterEngine.mm(294)] Could not launch engine with configuration.

**Comment by iampawan** [comment]
This might be helpful for you - https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated and not relevant to this project probably so closing it for now.
