### ISSUE TITLE
   ** BUILD FAILED **

### ISSUE THREAD

**Issue by prathapbez** [iampawan/Flutter-UI-Kit#3]
Hi Pawan,

Kindly help me in resolving the below issue.

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by iampawan** [comment]
Run pod install and it should fix this.

**Comment by prathapbez** [comment]
Thanks
