### ISSUE TITLE
Running "flutter packages get" in Flutter-UI-Kit-master

### ISSUE THREAD

**Issue by bhandaribhumin** [iampawan/Flutter-UI-Kit#32]
Getting error 

> Could not find a file named "packages/flutter_web/pubspec.yaml" in https://github.com/flutter/flutter_web e2728abe0058d8a268881d82061d81e0171bbe86.
> Running "flutter packages get" in Flutter-UI-Kit-master...              
> pub get failed (1)

<img width="1120" alt="Screenshot 2019-05-21 at 12 02 28 AM" src="https://user-images.githubusercontent.com/3336047/58043847-ed995480-7b5b-11e9-8bbe-20ad628264bd.png">

**Comment by bhandaribhumin** [comment]
any update

**Comment by rizwan-dev** [comment]
I too facing the same issue. Is there any way to fix this.

**Comment by bhandaribhumin** [comment]
@rizwan-dev nope brobbb

**Comment by NikoBr** [comment]
same here. Anyway to fix?

**Comment by JayPerfetto** [comment]
Same, have tried moving dependencies around but will likely just drop the web project for now

**Comment by JayPerfetto** [comment]
As a follow up, I stripped the web project out of this Kit, and had to replace all flutter_web/material references to be flutter/material -> this project is unusable until this issue is corrected, wherever the fault may reside

**Comment by bhandaribhumin** [comment]
Yes I also try everything like remove web dependences and download web dependency from git to my local directory but still same ☹️

**Comment by JayPerfetto** [comment]
> Yes I also try everything like remove web dependences and download web dependency from git to my local directory but still same ☹️

I managed to get this to a stable build without the web project, but there were a lot of bugs -> for instance, the assets directory is not included in the source anymore, and needed to be imported from an older version of this that I had on file...also the primary image path directory in UIData.dart was incorrect, and needed to have "assets/" added to "images"

**Comment by iampawan** [comment]
Try running flutter package global pub run webdev serve

**Comment by iampawan** [comment]
Checkout web_master master for running the web version of the app for now.

**Comment by bhandaribhumin** [comment]
@iampawan @JayPerfetto  thanks let me check and get back to you...

**Comment by bhandaribhumin** [comment]
@iampawan Everything is working fine thanks for your help also thanks @JayPerfetto
