### ISSUE TITLE
Got this warning, is this bad?

### ISSUE THREAD

**Issue by dannycortesv** [iampawan/Flutter-UI-Kit#34]
Having BuildContext _context; 

Generates this warning:

This class is marked as '@inmutable', but one or more of its instance fields are not final: LoginPage._context

so how can we have global vars?

Thanks for your help ;)

**Comment by iampawan** [comment]
It's not bad. But if you really need to use any non-final variable which is supposed to change then change the stateless widget to stateful and boom, the error is gone.

**Comment by dannycortesv** [comment]
Thanks for your help! Yes i did it, and boom the error was gone, haha.
