### ISSUE TITLE
Is this repository just a clickbait?

### ISSUE THREAD

**Issue by jonataslaw** [iampawan/Flutter-UI-Kit#35]
I downloaded the application, installed the repository and can not find the main layout described in the repository:

https://github.com/iampawan/Flutter-UI-Kit/raw/master/raw/fu12.png

I did not find it, or is it clickbait?
Just the layout defined as cover and described as "Flutter Ui Kit" does not exist in the repository.

**Comment by csmartin1024** [comment]
@jonataslaw 
Not sure how a github repo would ever be clickbait as you can see the code, but no it is not clickbait. I can confirm that view is for iOS so please run the app and install it to the iOS simulator. 
I had to run `pod install` from the ios directory prior to running this as a flutter app with vs code. Proof is in the attachment 
![Simulator Screen Shot - iPhone Xʀ - 2019-05-31 at 23 37 12](https://user-images.githubusercontent.com/16888039/58744861-48a13600-83fd-11e9-9a1c-584da06c040b.png)

**Comment by iampawan** [comment]
As mentioned by @csmartin1024 that the view was made only for ios. But saying it clickbait is also not a good idea to ask this question. Anyway closing it.
