### ISSUE TITLE
Gradlew

### ISSUE THREAD

**Issue by ADN09** [iampawan/Flutter-UI-Kit#36]
* Error running Gradle:
ProcessException: Process "C:\Users\YBECERRIL\Downloads\Flutter UI\android\gradlew.bat" exited abnormally:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\YBECERRIL\Downloads\Flutter UI\android\app\build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: C:\Users\YBECERRIL\Downloads\Flutter UI\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

**Comment by YuanTianyang** [comment]
I had the same problem

**Comment by YuanTianyang** [comment]
> * Error running Gradle:
>   ProcessException: Process "C:\Users\YBECERRIL\Downloads\Flutter UI\android\gradlew.bat" exited abnormally:
>   Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Build file 'C:\Users\YBECERRIL\Downloads\Flutter UI\android\app\build.gradle' line: 29
> * What went wrong:
>   A problem occurred evaluating project ':app'.
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> Command: C:\Users\YBECERRIL\Downloads\Flutter UI\android\gradlew.bat app:properties
> 
> Please review your Gradle project setup in the android/ folder.
> Exited (sigterm)

If you read the README, then you should be able to solve the problem!
The solution is in the "Building the project".

**Comment by iampawan** [comment]
Refer to readme
