### ISSUE TITLE
the named parameter 'hasNotch' isn't defined.

### ISSUE THREAD

**Issue by yin8080** [iampawan/Flutter-UI-Kit#4]
What is the reason?

**Comment by iampawan** [comment]
Which flutter version you are using?

**Comment by yin8080** [comment]
@iampawan flutter version 0.56-pre.61

**Comment by tonyhelloworld** [comment]
@iampawan I have the same problem. This 'hasNotch‘ attribute not fond. /lib/ui/widgets/common_scaffold

**Comment by tonyhelloworld** [comment]
After running this project, it will explode wrong!
Detailed erro:
* Error running Gradle:
Exit code 1 from: D:\xiangmu\Flutter-UI-Kit\android\gradlew.bat app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

**Comment by iampawan** [comment]
@tonyhelloworld flutter version?

**Comment by iampawan** [comment]
Change your flutter channel by typing "flutter channel beta or dev" in the terminal and then run the app once.

**Comment by tonyhelloworld** [comment]
@iampawan OK，Let me try

**Comment by tonyhelloworld** [comment]
@iampawan Please help me!
 `$ flutter --version
Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (4 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

Unfortunately i will not be able to use it!!! It was the same mistake last time
Detail erro:
---------------------------
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: D:\work\Flutter-UI-Kit\android\gradlew.bat app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\work\Flutter-UI-Kit\android\app\build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':app'.
> D:\work\Flutter-UI-Kit\android\key.properties (系统找不到指定的文件。)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Finished with error: Please review your Gradle project setup in the android/ folder.
--------------------------
what should i do

**Comment by iampawan** [comment]
@tonyhelloworld Check the documentation to see how to build the project and then it will fix the issue.

**Comment by tonyhelloworld** [comment]
@iampawan ok,I known

**Comment by tonyhelloworld** [comment]
@iampawan Thank you

**Comment by iampawan** [comment]
@tonyhelloworld Did it work? If yes, then I'll close the issue.

**Comment by tonyhelloworld** [comment]
@iampawan I don't know how to solve this problem right now. you close the issue.

Maybe it's my file permissions.
Thank you in the end

**Comment by iampawan** [comment]
Whats the error?

**Comment by tonyhelloworld** [comment]
@iampawan ok，The problem has been solved.i am should read more of your documents!!! After a reminder.
Read your https://github.com/iampawan/Flutter-UI-Kit#user-content-missing-keyproperties-file.i Understand.
I am rookie
