### ISSUE TITLE
I open Shopping Details " No top-level method '' declared."

### ISSUE THREAD

**Issue by wublack** [iampawan/Flutter-UI-Kit#5]
Detail Info:
Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
Application show this:
![screenshot_2018-07-04-14-54-10-741_com mtechviral flutteruikit](https://user-images.githubusercontent.com/10573644/42261266-399c94be-7f9a-11e8-9191-736780e4b645.png)

Flutter info:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.5.6, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Ultimate Edition (version 2017.2)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by wublack** [comment]
More Info:
I/flutter (13158): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13158): The following NoSuchMethodError was thrown building CommonScaffold(dirty):
I/flutter (13158): No top-level method '' declared.
I/flutter (13158): Receiver: top-level
I/flutter (13158): Tried calling: (hasNotch: true, child: Instance of 'Ink')
I/flutter (13158): When the exception was thrown, this was the stack:
I/flutter (13158): #0      CommonScaffold.myBottomBar (package:flutter_uikit/ui/widgets/common_scaffold.dart)
I/flutter (13158): #1      CommonScaffold.build (package:flutter_uikit/ui/widgets/common_scaffold.dart:124:44)
I/flutter (13158): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3708:28)
I/flutter (13158): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (13158): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (13158): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (13158): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (13158): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (13158): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (13158): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (13158): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #58     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (13158): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (13158): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #71     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (13158): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (13158): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #87     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (13158): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #99     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (13158): #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (13158): #106    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (13158): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (13158): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (13158): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (13158): #110    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4450:32)
I/flutter (13158): #111    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4782:17)
I/flutter (13158): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (13158): #113    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (13158): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (13158): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #117    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter (13158): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (13158): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #121    ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter (13158): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (13158): #123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (13158): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (13158): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #127    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter (13158): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (13158): #129    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (13158): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (13158): #131    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (13158): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (13158): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (13158): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (13158): #135    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter (13158): #136    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (13158): #137    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (13158): #138    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13158): #139    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (13158): #140    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (13158): #141    _invoke (dart:ui/hooks.dart:120:13)
I/flutter (13158): #142    _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (13158): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by iampawan** [comment]
Fixed in latest commit.

**Comment by iampawan** [comment]
If you still face the issue after updating then please reopen the issue. thanks

**Comment by MuhammadIkhsan21** [comment]
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building Icon(IconData(U+0E53A), size: 24.0, dirty):
flutter: No top-level method '' declared.
flutter: Receiver: top-level
flutter: Tried calling: (child: Instance of 'RichText')
flutter:
flutter: When the exception was thrown, this was the stack:

can you help me,
i dont show icon in flutter?
@iampawan
